sonar.projectKey=pickles-website
sonar.projectName=pickles-website
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/terraform/**,**/.git/**,**/build/**,**/coverage/**
sonar.sourceEncoding=UTF-8
